### ISSUE TITLE
Why is Apache installed ?

### ISSUE THREAD

**Issue by jillro** [ansible/distro-test-containers#102]
Is there any reason apache2 is installed on Ubuntu images ? It breaks any integration test which rely on port 80 being available.

**Comment by mattclay** [comment]
It used to be included (along with various other packages) to improve test performance, but that was before most modules (and tests) were split out into collections.

The distro containers are overdue for a review of installed packages. Until that happens, there are a few options:

1) If possible, use a different port for tests to avoid the conflict.
2) Stop the apache service at the start of the test. Consider restarting the service at the end of the test if it was stopped.
