### ISSUE TITLE
 ansible: command not found in ubuntu1604-test-container

### ISSUE THREAD

**Issue by patsevanton** [ansible/distro-test-containers#12]
Hello!
I try run ansible in quay.io/ansible/ubuntu1604-test-container
but get error
```
$ ansible
/bin/bash: line 70: ansible: command not found
ERROR: Job failed: exit code 1
```

Repository: https://gitlab.com/anton_patsev/ansible-ubuntu1604-test-container
Log: https://gitlab.com/anton_patsev/ansible-ubuntu1604-test-container/-/jobs/128296998

**Comment by mattclay** [comment]
@patsevanton These containers are used for integration testing of Ansible. They do not contain any release of Ansible and are not intended for deploying or running Ansible.

For installation of Ansible, see the [installation guide](https://docs.ansible.com/ansible/devel/installation_guide/intro_installation.html#installing-the-control-machine).
