### ISSUE TITLE
Debian Image

### ISSUE THREAD

**Issue by aminvakil** [ansible/distro-test-containers#47]
Is there any specific reason there isn't a debian image?

**Comment by mattclay** [comment]
We haven't encountered any significant issues in our testing where we felt that coverage using Ubuntu was inadequate.

Is there a specific case you're interested in seeing covered with Debian?

**Comment by aminvakil** [comment]
> Is there a specific case you're interested in seeing covered with Debian?

No, but I assume if there is a problem, we'll never know if we don't test it.

Although I don't know about legal or cost issues of adding debian image to test and is it worth or not.

**Comment by aminvakil** [comment]
I'll try creating a Debian 10 docker image locally and run integration tests against it, I will paste the results here to see if there was anything not caught by Ubuntu tests or any other interesting stuff.

**Comment by aminvakil** [comment]
I've tested all integration tests (except cloud tests) using this docker image:
https://github.com/aminvakil/distro-test-containers/tree/debian10_dockerfile/debian10-test-container

Some tests were skipped as they only get tested by Ubuntu containers, but I've found three errors:
https://github.com/ansible/ansible/pull/72138
https://github.com/ansible/ansible/pull/72139
http://ix.io/2zZH (I don't know how to fix it correctly).

Therefore I think my concern was not appropriate.
